### ISSUE TITLE
File extension after upload

### ISSUE THREAD

**Issue by fiusuki** [juliomalegria/django-chunked-upload#15]
Hi,
I tested your app, using your demo, and when the download finishes the file extension keeps as ".part".
Am I doing something wrong?
Thanks for this product!

**Comment by juliomalegria** [comment]
Hey @fiusuki,
So the way `django-chunked-upload` works is it creates a file called `<upload_id>.part`, and it uses it to append the chunks you send on each request.
Once you finish uploading all the chunks and send the `/complete` request, the `on_completion`method will be called, and the uploaded file will be passed as a parameter.
In this method is where you'd implement whatever logic you want to do with that file. Could be store it somewhere in your media folder, associate it to a model's instance, open the file and analyze/parse it, etc. That's entirely up to you.
In the demo, [the `on_completion` method is not doing anything](https://github.com/juliomalegria/django-chunked-upload-demo/blob/master/demo/views.py#L30), that's why you only see the `.part` file.
I hope that answers your question :)

**Comment by fiusuki** [comment]
Perfect!
Thanks for your answer! :)
