### ISSUE TITLE
Automatically clean up of chunked_uploads directories at upload completion

### ISSUE THREAD

**Issue by PaulDDD** [juliomalegria/django-chunked-upload#23]
Hello

I may have missed this somewhere. But is it possible to get the chunked upload directory to automatically clean up at upload completion?

My upload completion assigns the file to a model file field, which results in the file being copied to a new location. However, the chunked_upload '.part' data accumulates.

Thanks!

**Comment by juliomalegria** [comment]
Hi there,

Sorry for the (very) late response. There are a couple of ways to do what you want:

* You can override the [on_completion()](https://github.com/juliomalegria/django-chunked-upload/blob/master/chunked_upload/views.py#L232) method of ChunkedUploadCompleteView [1] to delete the instance once you've used the uploaded file (saved it somewhere else, processed it, etc.). When deleting the instance, don't forget to pass delete_file=True (see [BaseChunkUpload.delete](https://github.com/juliomalegria/django-chunked-upload/blob/master/chunked_upload/models.py#L61)).

* The problem with the previous solution is that the incomplete or failing ChunkedUploads will pile up (since they never get to run on_completion). So the other option is to run the management command [delete_expired_upload](https://github.com/juliomalegria/django-chunked-upload/blob/master/chunked_upload/management/commands/delete_expired_uploads.py). This commands cleans the inactive chunks based on [CHUNKED_UPLOAD_EXPIRATION_DELTA](https://github.com/juliomalegria/django-chunked-upload#chunked_upload_expiration_delta). You can use a cron job to run this once a day/week/etc. Read [StackOverflow: Django custom command and cron](http://stackoverflow.com/q/1601153/972208) for how to do this.
