### ISSUE TITLE
strange code

### ISSUE THREAD

**Issue by insideable** [juliomalegria/django-chunked-upload#26]
Hi, 
is the following code correct? strftime for filename looks a bit strange for me :) 
https://github.com/juliomalegria/django-chunked-upload/blob/master/chunked_upload/models.py#L23

**Comment by juliomalegria** [comment]
Hi @insideable,
This is because the default [UPLOAD_PATH](https://github.com/juliomalegria/django-chunked-upload/blob/master/chunked_upload/settings.py#L24) is `'chunked_uploads/%Y/%m/%d'`. We use `time.strftime` to fill those placeholders, or any others that could be set.

If the path doesn't vary by date, then `time.strftime` won't alter it:

    time.strftime('helloworld') == 'helloworld'
