### ISSUE TITLE
md5 hash

### ISSUE THREAD

**Issue by shaw2thefloor** [juliomalegria/django-chunked-upload#8]
Hi Julio, I hope you had a good Christmas. 

With the final call to ChunkedUploadCompleteView, I assume the checksum has to be the md5 for the whole file which has been uploaded? I am looking to upload very large files (like 10s of GB). Creating an md5 on the client side seems to be rather a slow process. Do you have any suggestions for the best way to accomplish this? Using https://github.com/satazor/SparkMD5, it takes about 40 seconds to compute an md5 hash for a 5GB file!

**Comment by hackdna** [comment]
I'm in a similar situation, except the files are 30GB+ and we do need the checksums to ensure data integrity. However, if I wanted to display a checksum for an uploaded file to the user this would take a few minutes to calculate every time. Would it be possible to make `md5` a model field instead of a property?
